const fs=require("fs");
let c=fs.readFileSync("app/dashboard/core/pentagon/page.tsx","utf8");
c=c.replace(/pentagon\.totalSpvs/g,"spvs.length");
c=c.replace(/pentagon\.sectors/g,"new Set(spvs.map(s=>s.sector)).size");
c=c.replace(/pentagon\.totalBudget/g,"spvs.reduce((s,p)=>s+(p.totalBudget||0),0)");
c=c.replace(/pentagon\.active/g,"spvs.filter(s=>s.status===\"aktivan\").length");
c=c.replace(/pentagon\.completed/g,"spvs.filter(s=>s.status===\"zavrsen\").length");
c=c.replace(/pentagon\.blocked/g,"blockedSpvs.length");
fs.writeFileSync("app/dashboard/core/pentagon/page.tsx",c,"utf8");
console.log("OK");
